# Generated by Django 2.2.7 on 2019-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=800)),
                ('url_level', models.IntegerField()),
                ('parent_id', models.IntegerField(null=True)),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('keywords', models.CharField(default='', max_length=200, null=True)),
                ('description', models.CharField(default='', max_length=5000, null=True)),
                ('flag', models.IntegerField()),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
